=== Adri11037/PROYECTO_LEMA/plantilla/winx.dtd
<!ELEMENT COLECCION (INTRODUCCION,DESCRIPCION_SERIE,LOGO,IVA,TEMPORADAS,PERSONAJES,CRIATURAS,PRODUCTOS,VESTUARIOS)>
<!ELEMENT INTRODUCCION (#PCDATA)>
<!ELEMENT DESCRIPCION_SERIE (PARRAFO*)>
<!ELEMENT PARRAFO (#PCDATA)>
<!ELEMENT LOGO (#PCDATA)>
<!ELEMENT IVA (#PCDATA)>
<!ELEMENT TEMPORADAS (TEMPORADA+,EXISTENCIAS_TOTALES)>
<!ELEMENT TEMPORADA (NOMBRE,TRAMA,VILLANOS,TRANSFORMACIONES,IMAGEN,DVD,PRECIO,DESCUENTO,EXISTENCIAS,WEB)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT TRAMA (#PCDATA)>
<!ELEMENT VILLANOS (#PCDATA)>
<!ELEMENT TRANSFORMACIONES (TRANSFORMACION_PRINCIPAL?,SUB-TRANSFORMACIONES?,TRANSFORMACION_INICIAL?,TRANSFORMACION_FINAL?)>
<!ELEMENT TRANSFORMACION_PRINCIPAL (#PCDATA)>
<!ELEMENT IMAGEN (#PCDATA)>
<!ELEMENT DVD (#PCDATA)>
<!ELEMENT PRECIO (#PCDATA)>
<!ELEMENT DESCUENTO (#PCDATA)>
<!ELEMENT EXISTENCIAS (#PCDATA)>
<!ELEMENT WEB (#PCDATA)>
<!ELEMENT SUB-TRANSFORMACIONES (TRANSFORMACION+)>
<!ELEMENT TRANSFORMACION (#PCDATA)>
<!ELEMENT TRANSFORMACION_INICIAL (#PCDATA)>
<!ELEMENT TRANSFORMACION_FINAL (#PCDATA)>
<!ELEMENT EXISTENCIAS_TOTALES EMPTY>
<!ELEMENT PERSONAJES (PERSONAJE+)>
<!ELEMENT PERSONAJE (INFORMACION)>
<!ATTLIST PERSONAJE id ID #REQUIRED>
<!ELEMENT INFORMACION (#PCDATA)>
<!ELEMENT CRIATURAS (PIXIES,SELKIES,ANIMALES_MAGICOS)>
<!ELEMENT PIXIES (QUE_SON,PIXIES_GUARDIANAS,PIXIE+)>
<!ELEMENT QUE_SON (#PCDATA)>
<!ELEMENT PIXIES_GUARDIANAS (PIXIE+)>
<!ELEMENT PIXIE (NOMBRE,GUARDIANA?,IMG,HABILIDADES?)>
<!ELEMENT GUARDIANA (#PCDATA)>
<!ELEMENT IMG (#PCDATA)>
<!ELEMENT HABILIDADES (#PCDATA)>
<!ELEMENT SELKIES (DESCRIPCION,QUE_SON,SELKIE+)>
<!ELEMENT DESCRIPCION (#PCDATA)>
<!ELEMENT SELKIE (NOMBRE,GUARDIANA,VINCULACION,IMG)>
<!ELEMENT VINCULACION (#PCDATA)>
<!ELEMENT ANIMALES_MAGICOS (ANIMAL+)>
<!ELEMENT ANIMAL (NOMBRE,CARACTERISTICAS,TIPO,IMG)>
<!ELEMENT CARACTERISTICAS (#PCDATA)>
<!ELEMENT TIPO (#PCDATA)>
<!ATTLIST TIPO inclinacion (inofensiva|maligna|neutral) #REQUIRED>
<!ELEMENT PRODUCTOS (CARTAS,OBJETOS_MAGICOS,EXISTENCIAS_TOTALES)>
<!ELEMENT CARTAS (WINXS,ESPECIALISTAS,BRUJAS)>
<!ELEMENT WINXS (CARTA+)>
<!ELEMENT CARTA (NOMBRE,DESCRIPCION_PERSONAJE,IMG,PRECIO,DESCUENTO,EXISTENCIAS,WEB)>
<!ATTLIST CARTA id IDREF #REQUIRED>
<!ELEMENT DESCRIPCION_PERSONAJE (#PCDATA)>
<!ELEMENT ESPECIALISTAS (CARTA+)>
<!ELEMENT BRUJAS (CARTA+)>
<!ELEMENT OBJETOS_MAGICOS (OBJETO+)>
<!ELEMENT OBJETO (NOMBRE,IMG,DESCRIPCION,PRECIO,DESCUENTO,EXISTENCIAS,WEB)>
<!ATTLIST OBJETO tipo (accesorio|objeto) #REQUIRED>
<!ELEMENT VESTUARIOS (ROPA+,EXISTENCIAS_TOTALES)>
<!ELEMENT ROPA (NOMBRE,DESCRIPCION,IMG,PRECIO,DESCUENTO,EXISTENCIAS,WEB)>

=== Adri11037/PROYECTO_LEMA/plantilla/winx.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COLECCION SYSTEM "winx.dtd">
<?xml-model href="winx.xsd"?>

<!-- EXISTENCIAS_TOTALES: VARIABLE EN XSL-->


<COLECCION>
    <INTRODUCCION>En esta pagina descubriras tanto informacion acerca de la famosa serie "Winx Club"
        como articulos que podras comprar de esta</INTRODUCCION>
    <DESCRIPCION_SERIE>
        <PARRAFO>
        Las Hadas son criaturas mágicas que viven en la Dimensión Mágica. A lo largo
        de la serie, se han visto muchos tipos de hadas. Estos incluyen las hadas normales, al igual
        que las chicas Winx Alfea y otros estudiantes, así como otros seres mágicos como Arcadia,
        las hadas etéreas, y las hadas rústicas. Todas las hadas son en su mayoría humanoides en
        apariencia, con las hadas normales buscan exactamente igual que los humanos, pero con las
        alas cuando se transforma, mientras Arcadia y las hadas etéreas tienen unas características
        menos humanos y se parecen más a los seres puramente mágicos.
        </PARRAFO>
        
       
        <PARRAFO>La mayoría de las hadas se saben que han utilizado sus poderes para buenos propósitos y
        proteger la dimensión mágica de las fuerzas del mal, y han colaborado con otros seres
        mágicos como duendes, brujas y magos para luchar contra el mal, un ejemplo es la Compañía de
        Luz. Sin embargo, algunas de las hadas se sabe que se han aliado con las fuerzas del mal
        para sus propios motivos egoístas. Otras Hadas, mientras que en realidad no cambian al lado
        oscuro o aliarse con las fuerzas del mal, sin embargo han estado en el lado malo y hecho
        cosas malas</PARRAFO>
        
        
        <PARRAFO>Las Brujas (o Hechiceras) son criaturas mágicas de la Dimensión Mágica y son el polo opuesto
        de las hadas. Las brujas y los magos son similares en apariencia a los seres humanos y las
        hadas. Sin embargo, la fuente de sus poderes mágicos es proveniente a sus sentimientos
        negativos y de la oscuridad, mientras que las Hadas deriva a sus buenos sentimientos y de la
        luz.
        </PARRAFO>
        
       
        <PARRAFO>Para ello las brujas casualmente visten ropas oscuras, góticos, punks entre otros tipos de
        vestimentas. Aunque varias chicas tienen atuendos similares a las hadas pero con ciertos
        cambios.
        </PARRAFO>

        
        <PARRAFO>Incluso si algunas brujas han utilizado sus poderes para fines malignos, la mayoría de las
        brujas no son necesariamente malos, como se ha mencionado varias veces en la serie, siendo
        ejemplo Griffin quien ayudó a la Compañía de Luz para combatir contra lasBrujas Ancestrales
        (como un esfuerzo por haber inicialmente trabajado con las antepasadas y Valtor, aunque fue
        mencionada por Valtor que Griffin y Faragonda ya eran amigas cuando Griffin seguía con las
        antepasadas cuando dice que dejó las antepasadas a lado con su "gran amigo"), Faragonda (que
        era una bruja, pero más tarde se convirtió en un hada), Mirta, Lucy y muchas otras brujas de
        Torre Nubosa ayudaron a las hadas
        </PARRAFO>

        
        <PARRAFO>Las Hadas, brujas y seres humanos constituyen la parte principal de la sociedad de la
        dimensión mágica, la proporción de cada variable a través de los reinos, con otros seres
        mágicos como los elfos, ogros, Hechiceros y otros seres mágicos también están presentes en
        algunos ámbitos, y parece que las hadas suelen ser los principales miembros de las
        sociedades de la mayoría de los reinos de la Dimensión Mágica.
        </PARRAFO>
    </DESCRIPCION_SERIE>
    <LOGO>images/logo.png</LOGO>
    <IVA>21</IVA>
    <TEMPORADAS>
        <!-- POR CADA TEMPORADA PUEDE TENER O NO SUB-TRANFORMACIONES, NO ES OBLIGATORIO QUE LAS
             TENGA-->
        <TEMPORADA>
            <NOMBRE>1ªTemporada</NOMBRE>
            <TRAMA>Bloom, una chica normal del planeta Tierra, vive una vida perfectamente normal en
                la ciudad de Gardenia, hasta que conoce a Stella, un hada y princesa del planeta
                Solaria, la cual está metida en problemas. Al ir a ayudar a Stella, Bloom descubre
                sus poderes mágicos. Stella convence a Bloom de que se dirija a Alfea, la escuela
                para hadas considerada como la mejor de toda la dimensión mágica.
                
                En Alfea, Bloom crea el Winx Club, cuyas miembros son sus cuatro amigas y compañeras
                de habitación: Stella, Flora, Musa y Tecna. Más tarde, se encontrarán con los
                Especialistas de Fuente Roja, concretamente con Brandon, Riven, Timmy y
                Sky, quienes se convertirán en sus amigos e intereses amorosos. Las miembros del
                Winx Club también se involucrarán con un trío de brujas (hechiceras) de Torre de
                Nubes: Icy, Darcy y Stormy, a las que se referirán como las Trix.
                
                Las Trix van en busca del poder de la Llama del dragón y su persecución despiadada
                hace que tengan varios encuentros y luchas con el Winx Club. De esta manera, Bloom
                se embarcará en esta aventura y empezará a aprender los secretos de su verdadero
                planeta de procedencia, su familia y sus poderes.</TRAMA>
            <VILLANOS>Las Trix</VILLANOS>
            <TRANSFORMACIONES>
                <TRANSFORMACION_PRINCIPAL>Magic Winx</TRANSFORMACION_PRINCIPAL>
            </TRANSFORMACIONES>
            <IMAGEN>temporada1.webp</IMAGEN>
            <DVD>Contiene 26 capitulos</DVD>
            <PRECIO>19.00€</PRECIO>
            <DESCUENTO>10.00</DESCUENTO>
            <EXISTENCIAS>15</EXISTENCIAS>
            <WEB>https://winx.fandom.com/es/wiki/1%C2%AA_Temporada</WEB>
        </TEMPORADA>
        <TEMPORADA>
            <NOMBRE>2ªTemporada</NOMBRE>
            <TRAMA>Después de sus vacaciones de verano, el Club Winx regresa a Alfea para comenzar
                su segundo año. Se reúnen con una nueva hada, Laila, que pide su ayuda para rescatar
                a sus amigas Pixies tomadas como rehenes por Lord Darkar. Lord Darkar es en realidad
                el "Fénix de Sombras", un ser oscuro que quiere tener el control sobre toda la
                Dimensión Mágica. Con el fin de conseguirlo, tiene que averiguar dónde está la Aldea
                Pixie con el proposito de robar las cuatro piezas del Codex que abren el portal al
                reino de Realix, donde se puede encontrar el máximo poder. Las Trix se unen a Lord
                Darkar y actuan bajo su servicio. Mientras tanto, las Winx aprenden a realizar
                convergencia mágica, como asi tambien sobre el Charmix y como obtenerlo. Un nuevo
                "maestro" llega a Alfea y convierte a Bloom en Dark Bloom para que ella coopere con
                Lord Darkar. Con la ayuda de Dark Bloom, Lord Darkar abre el portal hacia el reino
                de Realix. Cuando todo parece perdido, en el último momento, Sky confiesa sus
                verdaderos sentimientos hacia Bloom, regresandola a su estado normal. Bloom se cura
                a si misma y a todos sus amigos y derrotan a Lord Darkar con una convergencia.
                Después de la batalla, Bloom y los demás vuelven a Alfea y celebran.</TRAMA>
            <VILLANOS>Lord Darkard y las trix</VILLANOS>
            <TRANSFORMACIONES>
                <TRANSFORMACION_PRINCIPAL>Charmix</TRANSFORMACION_PRINCIPAL>
            </TRANSFORMACIONES>
            <IMAGEN>temporada2.webp</IMAGEN>
            <DVD>Contiene 26 capitulos</DVD>
            <PRECIO>19.00€</PRECIO>
            <DESCUENTO>10.00</DESCUENTO>
            <EXISTENCIAS>3</EXISTENCIAS>
            <WEB>https://winx.fandom.com/es/wiki/2%C2%AA_Temporada</WEB>
        </TEMPORADA>
        <TEMPORADA>
            <NOMBRE>3ªTemporada</NOMBRE>
            <TRAMA>Las Winx empiezan su tercer año en Alfea y las chicas aprenden sobre una
                transformacion única, el Enchantix. Este nivel se consigue tras sacrificarse por
                alguien de su propio mundo. Mientras tanto, las Trix, que habían desaparecido y
                habían ido a la Dimensión Omega, escapan con Valtor, un hechicero en parte
                responsable por la destrucción de Domino, el reino de Bloom. Se deciden a cooperar y
                planean invadir varias zonas en el reino de Magix en busca de venganza sobre
                aquellos que los encarcelaron al robar los tesoros mágicos y las fuentes de poder de
                cada reino. Con sus nuevos poderes Enchantix Laila, Flora, Stella, Tecna y Musa son
                capaces de utilizar fuertes e increíbles hechizos magicos, también pueden
                miniaturizarse a si mismas. Bloom, por otra parte, al no haber nadie de su mundo a
                quien pudiera salvar, va a Pyros, la isla de los dragones, donde aprende a enfocar
                su energía y de esa forma obtiene la forma Enchantix, aun así Bloom no puede
                miniaturizarse porque que su Enchantix está incompleto. Al final de la temporada,
                Bloom conoce más detalles sobre Domino, como así también acerca del paradero de
                Oritel y Marion, sus padres biológicos.</TRAMA>
            <VILLANOS>Valtor y Las Trix</VILLANOS>
            <TRANSFORMACIONES>
                <TRANSFORMACION_PRINCIPAL>Enchantix</TRANSFORMACION_PRINCIPAL>
            </TRANSFORMACIONES>
            <IMAGEN>temporada3.jpg</IMAGEN>
            <DVD>Contiene 26 capitulos y una pelicula: "Winx Club: El Secreto del Reino Perdido"</DVD>
            <PRECIO>22.00€</PRECIO>
            <DESCUENTO>0.00</DESCUENTO>
            <EXISTENCIAS>50</EXISTENCIAS>
            <WEB>https://winx.fandom.com/es/wiki/3%C2%AA_Temporada</WEB>
        </TEMPORADA>
        <TEMPORADA>
            <NOMBRE>4ªTemporada</NOMBRE>
